### ISSUE TITLE
Second skin layer does not appear

### ISSUE THREAD

**Issue by Zohiu** [Pumpkin-MC/Pumpkin#1217]
### I've searched existing issues and couldn't find a duplicate.

- [x] I confirm this is not a duplicate.

### Operating System

NixOS unstable (commit 08dacfc)

### Server Software Version/Commit

Pumpkin 0.1.0-dev+1.21.10/2104367

### What happened?

When joining the server only the base skin layer appears.
This happens when joining directly with online-mode=true, when joining through a velocity proxy and also on the `pumpkin.kralverde.dev` server.
It also happens both on a fabric instance, and on a fresh install of vanilla 1.21.10

# Pumpkin server
<img width="531" height="258" alt="Image" src="https://github.com/user-attachments/assets/260f8604-4b21-4d77-8ff0-a0ef99abbf3d" />

# Singleplayer
<img width="682" height="315" alt="Image" src="https://github.com/user-attachments/assets/f4080eca-8f25-4f3a-bdd4-7ae164d0ee0e" />

### To Reproduce

1. Start a pumpkin server
2. Setup a fresh instance of Minecraft 1.21.10
3. Join the server

### Expected behavior

The second skin layer should appear like on other servers and in singleplayer.

**Comment by blaxkwidow** [comment]
fixed here https://github.com/Pumpkin-MC/Pumpkin/pull/1290

**Comment by MistDig** [comment]
<img width="307" height="401" alt="Image" src="https://github.com/user-attachments/assets/948de7c3-8dc3-4d20-a198-65bdd10b5f49" />

The second skin layer still do not load...

**Comment by Q2297045667** [comment]
> <img alt="Image" width="307" height="401" src="https://private-user-images.githubusercontent.com/216565119/625235198-948de7c3-8dc3-4d20-a198-65bdd10b5f49.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODQ3OTc3NTQsIm5iZiI6MTc4NDc5NzQ1NCwicGF0aCI6Ii8yMTY1NjUxMTkvNjI1MjM1MTk4LTk0OGRlN2MzLThkYzMtNGQyMC1hMTk4LTY1YmRkMTBiNWY0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNzIzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDcyM1QwOTA0MTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iMDQxODg4NzliNjk3Y2U5MmYxZmEwYzFjMWU5MzQ5MWI1MjliZjliMmIyYzQxMjRkYTk3OWYyNzY1NTFjNDkxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.qRdNKX0Ka4afiA885Dw-lE054FAewimliLfVGV_Ezus">
> The second skin layer still do not load...

Client version?

**Comment by Q2297045667** [comment]
> <img alt="Image" width="307" height="401" src="https://private-user-images.githubusercontent.com/216565119/625235198-948de7c3-8dc3-4d20-a198-65bdd10b5f49.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODQ5ODAzODEsIm5iZiI6MTc4NDk4MDA4MSwicGF0aCI6Ii8yMTY1NjUxMTkvNjI1MjM1MTk4LTk0OGRlN2MzLThkYzMtNGQyMC1hMTk4LTY1YmRkMTBiNWY0OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNzI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDcyNVQxMTQ4MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01MjgxYzZlNmJkNzRkYjMwZWE4M2UxODc2NWJmNjU2ZDA1NTVmZTNlNmFkMzM2MjA0MjgzZDNlYWI0YmU1NzNhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.RRRXfSoiXtQSLb1GGVCRtQvVwNn5SCSoIbM4ratXAeU">
> The second skin layer still do not load...

https://github.com/Pumpkin-MC/Pumpkin/pull/2525
